name: Rolling update with multiple environments

on:
  pull_request: :
      branches: 
        - main

jobs:
  Deployment:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1 
      matrix:
        environment:
          - server1
          - server2 
          - server3
    steps:
       - name: Deployment to different environment
         run:  echo "Deploying to ${{ matrix.environment }}"
